[project]
name = "lanchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "chromadb>=1.5.9",
    "ddgs>=9.16.0",
    "dotenv>=0.9.9",
    "ipykernel>=7.3.0",
    "langchain>=1.3.18",
    "langchain-community>=0.4.2",
    "langchain-huggingface>=1.2.2",
    "langchain-openai>=1.6.0",
    "langchain-text-splitters>=1.1.2",
    "openai>=3.7.0",
    "pandas>=3.0.5",
    "pypdf>=6.16.2",
    "python-dotenv>=1.2.3",
    "tiktoken>=0.14.0",
    "torch>=2.14.0",
    "transformers>=5.16.1",
    "wikipedia>=1.4.0",
]
